terraform-google-modules/terraform-google-bootstrap

README.md
examples/cloudbuild_enabled/main.tf
examples/simple/main.tf
main.tf
modules/cloudbuild/variables.tf
test/integration/cloudbuild_enabled/controls/gcp.rb
test/integration/simple/controls/gcp.rb

Adding examples for #14 & keeping list of APIs up to date for test fixtures.

feat: Implement examples of ensuring projectCreator rights are applied

---

CHANGELOG.md
README.md
main.tf
variables.tf

Add grant_billing_user variable

---

Makefile
examples/cloudbuild_enabled/main.tf
examples/simple-folder/main.tf
examples/simple/main.tf
modules/cloudbuild/README.md
modules/cloudbuild/cloudbuild_builder/Dockerfile
modules/cloudbuild/cloudbuild_builder/cloudbuild.yaml
modules/cloudbuild/main.tf
modules/cloudbuild/variables.tf
test/setup/main.tf
test/setup/versions.tf
versions.tf

Add terraform-validator binary and git to the container image.

feat: Add support for terraform validator

---

versions.tf

Downgrade minimum provider version, to provider better compatibility with existing code bases using the module

fix: downgrade minimum provider version

---

modules/cloudbuild/main.tf

Fixes https://github.com/terraform-google-modules/terraform-example-foundation/issues/129

fix: make trigger names generic now that multiple branches are supported

---

modules/cloudbuild/README.md

update the example module version

---

modules/cloudbuild/main.tf

Fixes:
https://github.com/terraform-google-modules/terraform-google-bootstrap/issues/52
https://github.com/terraform-google-modules/terraform-example-foundation/issues/208

fix: regex to only match the correct branches

---

versions.tf

fix: Required provider version upgraded to 0.12.20.

---

Makefile
README.md
build/int.cloudbuild.yaml
build/lint.cloudbuild.yaml
examples/cloudbuild_enabled/README.md
examples/cloudbuild_enabled/main.tf
examples/simple-folder/README.md
examples/simple-folder/main.tf
examples/simple/README.md
examples/simple/main.tf
kitchen.yml
main.tf
modules/cloudbuild/README.md
modules/cloudbuild/main.tf
modules/cloudbuild/versions.tf
test/fixtures/cloudbuild_enabled/versions.tf
test/integration/cloudbuild_enabled/controls/gcp.rb
test/integration/cloudbuild_enabled/inspec.yml
test/integration/simple-folder/inspec.yml
test/integration/simple/controls/gcp.rb
test/integration/simple/inspec.yml
test/setup/main.tf
versions.tf

- relax version constraints
- update inspec tests to 1.8
- update pf

feat: relax tf version to allow 0.13

---

modules/cloudbuild/main.tf

Fixes https://github.com/terraform-google-modules/terraform-google-bootstrap/issues/82

fix: Remove incorrect substitution for seed project

---

README.md
main.tf
variables.tf

Simple PR to add a `force_delete` variable for the state bucket.

add force_destroy

---

README.md
main.tf
modules/cloudbuild/README.md
modules/cloudbuild/main.tf
modules/cloudbuild/variables.tf
variables.tf

Will remove the need to do this here for the bucket https://github.com/terraform-google-modules/terraform-example-foundation/pull/393

feat: add ability to specify random suffix for projects and GCS

---

README.md
main.tf
variables.tf

added variable for terraform service account

---

modules/cloudbuild/main.tf

fix: Removes incompatible escape characters with Windows systems

---

main.tf
modules/cloudbuild/main.tf

chore: bump project-factory to ~> 11

---

main.tf

feat: add a lien for the seed project

---

docs/upgrading_to_v5.0.md
examples/cloudbuild_enabled/README.md
examples/cloudbuild_enabled/outputs.tf
modules/cloudbuild/README.md
modules/cloudbuild/main.tf
modules/cloudbuild/outputs.tf
test/fixtures/cloudbuild_enabled/outputs.tf
test/integration/cloudbuild_enabled/controls/gcp.rb
test/integration/cloudbuild_enabled/inspec.yml

fixes https://github.com/terraform-google-modules/terraform-google-bootstrap/issues/77

feat!: remove KMS resources in cloudbuild submodule

---

docs/upgrading_to_v5.0.md
docs/upgrading_to_v6.0.md
modules/cloudbuild/README.md
modules/cloudbuild/cloudbuild_builder/Dockerfile
modules/cloudbuild/cloudbuild_builder/cloudbuild.yaml
modules/cloudbuild/main.tf
modules/cloudbuild/variables.tf

https://github.com/terraform-google-modules/terraform-google-bootstrap/issues/153

feat!: Update Dockerfile to install terraform-validator from gcloud

---

outputs.tf

fix: wait on IAM to return terraform_sa_email

---

examples/tf_cloudbuild_workspace_simple/README.md
examples/tf_cloudbuild_workspace_simple/outputs.tf
modules/tf_cloudbuild_workspace/README.md
modules/tf_cloudbuild_workspace/buckets.tf
modules/tf_cloudbuild_workspace/cb.tf
modules/tf_cloudbuild_workspace/outputs.tf
test/integration/tf_cloudbuild_workspace_simple/tf_cloudbuild_workspace_simple_test.go

add an artifacts bucket to tf workspace module

add artifacts bucket to tf workspace module

---

examples/tf_cloudbuild_builder_simple/Dockerfile
modules/cloudbuild/cloudbuild_builder/Dockerfile

add terraform-tools to the docker images

---

modules/tf_cloudbuild_builder/README.md
modules/tf_cloudbuild_builder/cb.tf
modules/tf_cloudbuild_builder/variables.tf
modules/tf_cloudbuild_workspace/README.md
modules/tf_cloudbuild_workspace/cb.tf
modules/tf_cloudbuild_workspace/variables.tf

This PR creates a variable for providing the trigger location independent from the private pool id.

create variable for providing the trigger location

---

README.md
main.tf
outputs.tf
variables.tf

The Creation of the Terraform service account in the bootstrap module  should be optional.

Creation of the Terraform service account should be optional

---

modules/tf_cloudbuild_workspace/README.md
modules/tf_cloudbuild_workspace/buckets.tf
modules/tf_cloudbuild_workspace/sa.tf
modules/tf_cloudbuild_workspace/variables.tf

add custom name for cloud build service account and state bucket in the tf workspace module

feat: add custom name for cloud build service account and state bucket

---

README.md

chore: update credentials blog post

---

modules/tf_cloudbuild_builder/README.md
modules/tf_cloudbuild_builder/cb.tf
modules/tf_cloudbuild_builder/outputs.tf
modules/tf_cloudbuild_builder/variables.tf

This pull request adds a variable to allow to specify the timeout for cloudbuild.

feat: add timeout variable for cloudbuild builder

---

test/integration/im_cloudbuild_workspace_github/im_cloudbuild_workspace_github_test.go

Switch test to only use a single repository rather than create a new one every run, as the repository clean up wasn't working as expected.
Removed any code that wasn't being called now, such as creating/deleting repositories. Also bumped up the Cloud Build poll retry count, as I noticed it could creep up close to the 20 retry limit when testing.
Going to update other tests to use a single repository as well, in preparation for migration to a different user for the PAT.

fix: Use existing repo for IM Cloud Build GitHub module

---

test/integration/im_cloudbuild_workspace_gitlab/im_cloudbuild_workspace_gitlab_test.go

Switch test to use only a single project rather than create a new one every run, as project clean up isn't working as expected.
Removed code related to creating and deleting projects. Bumped up the Cloud Build poll retry count as well.

fix: Use existing repo for IM Cloud Build GitLab module

---

test/integration/cloudbuild_repo_connection_gitlab/cloudbuild_repo_connection_gitlab_test.go

Updating test to use a single repository rather than creating one per test, matching the behavior of the other tests.

chore(CI): Use single existing repository for tests

---

examples/tf_cloudbuild_workspace_simple_gitlab/scripts/push-to-repo.sh
test/integration/tf_cloudbuild_workspace_simple_gitlab/tf_cloudbuild_workspace_simple_gitlab_test.go
test/integration/utils/gitlab_client.go

Replaced use of the local GitLab client with the utils package one.

chore: Update CB workspace GL test to use existing repo

---

test/integration/cloudbuild_repo_connection_gitlab/cloudbuild_repo_connection_gitlab_test.go
test/integration/im_cloudbuild_workspace_gitlab/im_cloudbuild_workspace_gitlab_test.go

Will be easier to switch the testing user/group if all the tests can just use the single client. Also much more DRY.

chore: Switch GL clients to use utils package
