terraform-google-modules/terraform-google-bootstrap

CHANGELOG.md, README.md, examples/cloudbuild_enabled/main.tf, examples/simple/main.tf, main.tf, modules/cloudbuild/README.md, modules/cloudbuild/main.tf, modules/cloudbuild/variables.tf, modules/cloudbuild/versions.tf, test/integration/cloudbuild_enabled/controls/gcp.rb, test/integration/simple/controls/gcp.rb, variables.tf, versions.tf
This branch adds inputs for labels, changes the buckets to enforce Bucket Policy Only access, and adds Security Admin to the Terraform service account so that it can manage the created state.
@rjerrems FYI
=> Add labels, Bucket Policy Only, Security Admin role

main.tf, test/integration/cloudbuild_enabled/controls/gcp.rb
Adds permissions for org admins to the terraform state bucket conditionally if you are using impersonation.
=> Fix permissions issue in #5 for org admins using impersonation

examples/cloudbuild_enabled/main.tf, examples/simple/main.tf, main.tf, modules/cloudbuild/main.tf, modules/cloudbuild/variables.tf, modules/cloudbuild/versions.tf, variables.tf, versions.tf
BREAKING CHANGE: Upgrade to Project Factory 7.0, requiring Google Provider 3.x
=> Upgrade to Project Factory 7.0

test/integration/cloudbuild_enabled/controls/gcp.rb, test/integration/simple/controls/gcp.rb, variables.tf
Just adds serviceusage.googleapis.com in the default activated apis.
issue #10 
Note: I still have an issue for the tests to all pass with linking the billing account but I don't think it is any relevant to this change.
=> serviceusage api added in the default activate_apis (#10)

Makefile, README.md, build/int.cloudbuild.yaml, build/lint.cloudbuild.yaml, main.tf, modules/cloudbuild/README.md, modules/cloudbuild/main.tf, modules/cloudbuild/variables.tf, variables.tf
As discussed offline for https://github.com/terraform-google-modules/terraform-example-foundation/issues/61
- Adds skip_gcloud_download for all PF instances defaulting to `true`
- Also bumped PF to latest version
=> Add skip_gcloud_download for all PF instances

examples/cloudbuild_enabled/main.tf, examples/simple-folder/main.tf, examples/simple/main.tf, main.tf, modules/cloudbuild/main.tf
Hey folks!
This pull request closes the issue #62 replacing the `bucket_policy_only` for `uniform_bucket_level_access` parameter.
Could you please take a look?
Thanks!
=> Replaces deprecated bucket_policy_only for uniform_bucket_level_access

modules/cloudbuild/README.md, modules/cloudbuild/main.tf, modules/cloudbuild/variables.tf
Adds a new input variable `create_cloud_source_repos` (bool), whether CSR repos should be created. The default value is `true`.
This feature is useful for users that want to trigger Cloud Build outside of CSR (eg. [google_cloudbuild_trigger github](https://www.terraform.io/docs/providers/google/r/cloudbuild_trigger.html#github)).
=> feat: Make Cloud Source Repos optional

README.md, main.tf, modules/cloudbuild/README.md, modules/cloudbuild/main.tf, modules/cloudbuild/variables.tf, variables.tf
To fix issue #73. Adds a new input variable `project_id` (string) to be able override seed project id. This change is backward compatible. If default value is not changed, we use `project_prefix`.
=> feat: custom seed project id

modules/cloudbuild/versions.tf, test/fixtures/cloudbuild_enabled/versions.tf, versions.tf
As per
https://www.terraform.io/docs/configuration/version-constraints.html#terraform-core-and-provider-versions,
it is considered best practice not to have an upper version constraint.
Currently this module doesn't work with version 0.14.0
=> Remove upper terraform version constraint

Makefile, README.md, build/int.cloudbuild.yaml, build/lint.cloudbuild.yaml, examples/cloudbuild_enabled/main.tf, examples/simple-folder/main.tf, examples/simple/main.tf, main.tf, modules/cloudbuild/README.md, modules/cloudbuild/main.tf, modules/cloudbuild/variables.tf, modules/cloudbuild/versions.tf, test/setup/main.tf, variables.tf, versions.tf
This is required to support Terraform version 0.14. It is also a
breaking change because it dropped the `skip_gcloud_download` variable.
=> feat!: Upgrade google-project-factory to v10, add Terraform 0.13 constraint and module attribution

kitchen.yml, modules/cloudbuild/main.tf
Adds GAR repo name via substitutions in triggers to for usage in builds like https://github.com/terraform-google-modules/terraform-example-foundation/blob/f87ed1661bec7c2d2c75ea091d1cf5db6ac6943a/build/cloudbuild-tf-apply.yaml#L20
=> fix: expose GAR repo name via substitutions in triggers

modules/cloudbuild/cloudbuild_builder/Dockerfile
Fixes https://github.com/terraform-google-modules/terraform-google-bootstrap/issues/105
=> fix: Leave curl and unzip in Docker image

modules/cloudbuild/README.md, modules/cloudbuild/main.tf, modules/cloudbuild/variables.tf
When impersonating a service account in the google terraform provider, the background api calls are performed as that service account with one exception. There is one gcloud command being called locally where impersonation is not taken into account. This PR fixes that.
=> Allow service account impersonation in the local-exec gcloud runs.

modules/tf_cloudbuild_workspace/README.md, modules/tf_cloudbuild_workspace/cb.tf, modules/tf_cloudbuild_workspace/variables.tf
This PR adds support two options of `google_cloudbuild_trigger` resource.
- [`included_files`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger#included_files)
- [`ignored_files`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger#ignored_files)
=> feat: add support for `included_files` and `ignored_files` of `google_cloudbuild_trigger`

modules/tf_cloudbuild_builder/README.md, modules/tf_cloudbuild_builder/cb.tf, modules/tf_cloudbuild_builder/variables.tf, modules/tf_cloudbuild_workspace/README.md, modules/tf_cloudbuild_workspace/buckets.tf, modules/tf_cloudbuild_workspace/variables.tf
Add custom bucket names support for automatically created buckets:
- module `tf_cloudbuild_workspace`
- log_bucket
- artifacts_bucket
- module `tf_cloudbuild_builder`
- log_bucket
=> feat: Add custom bucket names support for modules `tf_cloudbuild_workspace` and `tf_cloudbuild_builder`

modules/im_cloudbuild_workspace/cb.tf, test/integration/im_cloudbuild_workspace_github/im_cloudbuild_workspace_github_test.go, test/setup/outputs.tf
Utilizes the random string present from setup. Also adjusted some resource name to reinforce string lengths based on the new repo name.
=> chore: Randomize repository names

modules/im_cloudbuild_workspace/templates/create-preview.sh.tftpl
Change the `gcloud` command to list the deployments filtered by the given ID. Should correctly match up with an existing deployment.
=> fix: Update check existing deployments command

examples/im_cloudbuild_workspace_github/main.tf, modules/im_cloudbuild_workspace/README.md, modules/im_cloudbuild_workspace/cb.tf, modules/im_cloudbuild_workspace/variables.tf, test/integration/im_cloudbuild_workspace_github/im_cloudbuild_workspace_github_test.go
Adds the `tf_version` variable which is used to pass to Infrastructure Manager and appending to the TF image provided.
Also added some Cleanup methods to the verify and teardown steps to close the pull request and delete the repository.
Tested locally by just running a gcloud command with some gibberish to trigger a fatal test error.
=> feat: Add tf_version variable for Infra Manager module

modules/im_cloudbuild_workspace/cb.tf, modules/im_cloudbuild_workspace/github.tf, modules/im_cloudbuild_workspace/gitlab.tf, modules/im_cloudbuild_workspace/repo.tf, test/integration/im_cloudbuild_workspace_github/im_cloudbuild_workspace_github_test.go
Cloud Build requires the suffix in order to create a connection, so we can just add it if it isn't given.
Updated the GitHub test to strip the ".git" suffix of the CloneURL to test the behavior.
=> feat: Add the ".git" suffix to the repo URL if missing

modules/im_cloudbuild_workspace/github.tf, modules/im_cloudbuild_workspace/gitlab.tf
Need to explicitly set which project is being used for the secret, otherwise it may not be able to determine which project to use.
Explicit tests are a little tricky to write because each bootstrapped project using in testing would need access to the secret. Open to doing that, but not sure the scope of changes needed for that (possibly at the CFT level).
=> feat: Set project field on secret IAM member

examples/cloudbuild_enabled/README.md, examples/cloudbuild_enabled/main.tf, examples/cloudbuild_enabled/variables.tf, modules/cloudbuild/README.md, modules/cloudbuild/main.tf, modules/cloudbuild/variables.tf, test/fixtures/cloudbuild_enabled/main.tf, test/fixtures/cloudbuild_enabled/variables.tf
This is a proposed fix for issue #146
=> fix: Added new force_destroy variable to cloudbuild module.

docs/upgrading_to_v10.0.md, docs/upgrading_to_v9.0.md, examples/tf_cloudbuild_builder_simple/main.tf, examples/tf_cloudbuild_builder_simple_github/main.tf, examples/tf_cloudbuild_builder_simple_gitlab/main.tf, modules/tf_cloudbuild_builder/README.md, modules/tf_cloudbuild_builder/variables.tf, modules/tf_cloudbuild_builder/workflow.tf
Add workflow deletion protection to cloud build builder module
=> feat!: add workflow deletion protection to cloud build builder module

modules/tf_cloudbuild_source/main.tf
This PR adds a depends_on inside the `tf_cloudbuild_source` 
to fix the following error on a retry after partial execution where the random suffix used to create the project ID exists but the project was not created
```
│ Error: Error when reading or editing GCS service account not found: googleapi: Error 400: Unknown project id: tf-cloudbuild--a30a, invalid
│ 
│   with module.tf_source.module.cloudbuild_bucket.data.google_storage_project_service_account.gcs_account,
│   on .terraform/modules/tf_source.cloudbuild_bucket/modules/simple_bucket/main.tf line 129, in data "google_storage_project_service_account" "gcs_account":
│  129: data "google_storage_project_service_account" "gcs_account" {
```
=> fix: add depends_on for cloudbuild_project module on cloudbuild_bucket module

examples/tf_cloudbuild_builder_simple_github/scripts/push-to-repo.sh, test/integration/tf_cloudbuild_builder_simple_github/tf_cloudbuild_builder_simple_github_test.go
Matching behavior of the other tests to avoid the issue of repositories not being cleaned up properly.
=> fix: Update test to use single existing repository

test/integration/cloudbuild_repo_connection_github/cloudbuild_repo_connection_github_test.go, test/integration/im_cloudbuild_workspace_github/im_cloudbuild_workspace_github_test.go, test/integration/tf_cloudbuild_builder_simple_github/tf_cloudbuild_builder_simple_github_test.go
Will be easier to switch the testing user/group if all the tests can just use the single client. Also much more DRY.
=> chore: Switch GH clients to use utils package
